from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any


class DifyClient:
    """Legacy Dify Workflow HTTP client.

    Python sends structured inputs to Dify and reads structured outputs back.
    Prompts, vision reasoning, reply generation, and learning logic stay in Dify.
    """

    def __init__(
        self,
        api_key: str | None,
        api_base: str = "https://api.dify.ai/v1",
        user: str = "memory-agent",
        timeout: int = 60,
    ) -> None:
        self.api_key = api_key
        self.api_base = api_base.rstrip("/")
        self.user = user
        self.timeout = timeout

    def run_workflow(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Run Dify Workflow once.

        The legacy sequential MemoryAgent passes task markers such as
        retrieval_query and learning. New GraphMemoryAgent code does not use
        this client.
        """
        if not self.api_key:
            return self._mock_response(inputs)

        url = f"{self.api_base}/workflows/run"
        payload = {
            "inputs": inputs,
            "response_mode": "blocking",
            "user": self.user,
        }
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        request = urllib.request.Request(
            url,
            data=body,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
        )

        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"Dify request failed: {exc.code} {detail}") from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(f"Dify request failed: {exc.reason}") from exc

    def _mock_response(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Local mock output for running the backend without DIFY_API_KEY."""
        stage = inputs.get("stage")
        chat_text = inputs.get("chatText", "")
        user_input = inputs.get("user_input", "")

        if stage == "intent_classifier":
            intent = self._mock_intent(user_input)
            return {
                "intent": intent,
                "input_summary": user_input,
            }

        if stage == "reply":
            return {
                "reply": {
                    "should_reply": True,
                    "content": self._mock_reply_content(inputs),
                    "reason": "Mock reply generated by local DifyClient.",
                }
            }

        if stage == "ocr":
            return {
                "chat_context": {
                    "recent_messages": [
                        {"role": "target", "content": "ok"},
                        {"role": "me", "content": user_input or "what should I reply?"},
                    ],
                    "previous_recent_messages": [],
                },
                "working_memory_observations": [
                    {
                        "content": "The latest conversation may need a concise reply.",
                        "confidence": 0.72,
                    }
                ],
            }

        if stage == "retrieval_query":
            return {
                "retrieval_query": inputs.get("input_summary") or chat_text or user_input,
            }

        if stage == "learning":
            return {
                "memory_updates": [
                    {
                        "memory_type": "conversation_style",
                        "content": "The user may prefer concise, low-pressure replies.",
                        "confidence": 0.82,
                        "has_conflict": False,
                    }
                ],
                "memory_reviews": [],
                "changed_summary": "Memory profile updated from latest context.",
            }

        return {
            "reply": {"should_reply": True, "content": "Mock response.", "reason": "fallback"},
            "memory_updates": [
                {
                    "memory_type": "conversation_style",
                    "content": "The user may react weakly to frequent follow-up questions.",
                    "confidence": 0.82,
                    "has_conflict": False,
                }
            ],
            "memory_reviews": [],
            "updated_working_memory": {
                "content": f"Latest chat context: {chat_text}",
                "confidence": 0.74,
            },
        }

    def _mock_intent(self, user_input: str) -> str:
        text = user_input.lower()
        if any(token in text for token in ("短一点", "自然一点", "改", "revise")):
            return "revise_reply"
        if any(token in text for token in ("记一下", "画像", "profile", "remember")):
            return "profile_update"
        if any(token in text for token in ("怎么回", "回复", "reply advice", "advice")):
            return "reply_advice"
        return "general_question"

    def _mock_reply_content(self, inputs: dict[str, Any]) -> str:
        intent = inputs.get("intent")
        if intent == "profile_update":
            return "已更新画像。"
        if intent == "revise_reply":
            return "可以，改得更短更自然。"
        if intent == "reply_advice":
            return "可以先轻松回应一句，别继续追问。"
        return f"这是一个本地 mock 回答：{inputs.get('user_input', '')}"
